In [1]:
# 1. dataset <- titanic.csv
import pandas as pd 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
import pandas as pd 
import numpy as np 

dataset = pd.read_csv('titanic.csv')
print(dataset)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [2]:
# 2.a Validation model dengan metode Hold Out 
from sklearn.model_selection import train_test_split
datalabel = dataset.loc[:, ['Survived']]
xtrainHold, xtestHold, ytrainHold, ytestHold = train_test_split(dataset.loc[:,
                                                dataset.columns != 'Survived'],
                                                datalabel, test_size = 0.30, 
                                                random_state=100) 


In [3]:
# Print xtrainHold
print(xtrainHold)

     PassengerId  Pclass                                               Name  \
69            70       3                                  Kink, Mr. Vincenz   
85            86       3  Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...   
794          795       3                              Dantcheff, Mr. Ristiu   
161          162       2  Watt, Mrs. James (Elizabeth "Bessie" Inglis Mi...   
815          816       1                                   Fry, Mr. Richard   
..           ...     ...                                                ...   
855          856       3                         Aks, Mrs. Sam (Leah Rosen)   
871          872       1   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)   
835          836       1                        Compton, Miss. Sara Rebecca   
792          793       3                            Sage, Miss. Stella Anna   
520          521       1                              Perreault, Miss. Anne   

        Sex   Age  SibSp  Parch      Ticket     Far

In [4]:
# print xtestHold
print(xtestHold)

     PassengerId  Pclass                           Name     Sex   Age  SibSp  \
205          206       3     Strom, Miss. Telma Matilda  female   2.0      0   
44            45       3  Devaney, Miss. Margaret Delia  female  19.0      0   
821          822       3              Lulic, Mr. Nikola    male  27.0      0   
458          459       2            Toomey, Miss. Ellen  female  50.0      0   
795          796       2             Otter, Mr. Richard    male  39.0      0   
..           ...     ...                            ...     ...   ...    ...   
111          112       3           Zabour, Miss. Hileni  female  14.5      1   
730          731       1  Allen, Miss. Elisabeth Walton  female  29.0      0   
105          106       3          Mionoff, Mr. Stoytcho    male  28.0      0   
479          480       3       Hirvonen, Miss. Hildur E  female   2.0      0   
277          278       2    Parkes, Mr. Francis "Frank"    male   NaN      0   

     Parch        Ticket      Fare Cabi

In [5]:
# Print ytrainHold
print(ytrainHold)

     Survived
69          0
85          1
794         0
161         1
815         0
..        ...
855         1
871         1
835         1
792         0
520         1

[623 rows x 1 columns]


In [6]:
# Print ytestHold
print(ytestHold)

     Survived
205         0
44          1
821         1
458         1
795         0
..        ...
111         0
730         1
105         0
479         1
277         0

[268 rows x 1 columns]


In [7]:
# 2.b Validation model dengan metode k-Fold
from sklearn.model_selection import KFold

kf=KFold(n_splits=10, random_state=0, shuffle=True)
p=0
for train_index, test_index in kf.split(dataset):
    p=p+1
    xtrain=dataset.loc[train_index]
    xtest=dataset.loc[test_index]
    xtrainHold=xtrain.loc[:, dataset.columns != 'Survived']
    xtestHold=xtest.loc[:, dataset.columns != 'Survived']
    ytrainHold=xtrain.loc[:,['Survived']]
    ytestHold=xtest.loc[:,['Survived']]

In [8]:
# Print ytrain
print(ytrainHold)

     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[802 rows x 1 columns]


In [9]:
# 2.c Validation model dengan metode k-Fold
from sklearn.model_selection import LeaveOneOut

loo=LeaveOneOut()
n=loo.get_n_splits(dataset)
for xtrainLoo, xtestLoo in loo.split(dataset):
    xtrainLoo = dataset.filter(items=xtrainLoo, axis=0)
    xtestLoo = dataset.filter(items=xtestLoo, axis=0)
ytrainLoo=xtrainLoo.loc[:, ['Survived']]
ytestLoo=xtestLoo.loc[:, ['Survived']]

xtrainLoo = xtrainLoo.loc[:, dataset.columns != 'Survived']
xtestLoo = xtestLoo.loc[:, dataset.columns != 'Survived']

In [10]:
print(ytrainHold)

     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[802 rows x 1 columns]


In [11]:
"""
3. train_data <- ambil dataset kolom fitur (Sex, Age, Pclass, Fare). Lakukan pengisian
missing value pada fitur Age dengan nilai mean dari masing-masing class
"""
import pandas as pd 

dataset = pd.read_csv('titanic.csv')
train_data = dataset[['Sex', 'Age', 'Pclass', 'Fare']]

print("Dataset sebelum pengisian \n", dataset.head())

# Konversi kolom 'Sex' ke nilai numeric
train_data['Sex'] = train_data['Sex'].map({'male': 1, 'female': 0})
train_data['Age'] = train_data.groupby('Pclass')['Age'].transform(lambda x: x.fillna(x.mean()))

print("Data setelah pengisian missing value 'Age' : \n ", train_data.head())


Dataset sebelum pengisian 
    PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450 

C:\Users\USER\AppData\Local\Temp\ipykernel_16272\3942152590.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data['Sex'] = train_data['Sex'].map({'male': 1, 'female': 0})
C:\Users\USER\AppData\Local\Temp\ipykernel_16272\3942152590.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data['Age'] = train_data.groupby('Pclass')['Age'].transform(lambda x: x.fillna(x.mean()))


In [12]:
# 4. label <- ambil dataset kolom kelas (Survived)
import pandas as pd 

dataset = pd.read_csv('titanic.csv')
label = dataset['Survived']

# Tampil hasil 
print("Label (Survived): \n", label.head())

Label (Survived): 
 0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64


In [13]:
"""
5. train_data <- lakukan normalisasi pada train_data dengan Min-Max 0-1 (catat nilai
min dan max setiap atribut)
"""
from sklearn.model_selection import train_test_split, KFold, LeaveOneOut
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import numpy as np

# Inisialisasi Min-Max Scaler
sc = MinMaxScaler(feature_range=(0, 1))

# 1. Metode Hold-out (70% train, 30% test)
xtrainHold, xtestHold, ytrainHold, ytestHold = train_test_split(train_data, label, test_size=0.3, random_state=42)

# Normalisasi Hold-out
train_dataHold = sc.fit_transform(xtrainHold)
test_dataHold = sc.transform(xtestHold)
print("Hasil normalisasi test_data Hold-out:\n", test_dataHold)

# 2. Metode K-Fold (k=10)
kf = KFold(n_splits=10, shuffle=True, random_state=42)

for train_index, test_index in kf.split(train_data):
    xtrainFold, xtestFold = train_data.iloc[train_index], train_data.iloc[test_index]
    ytrainFold, ytestFold = label.iloc[train_index], label.iloc[test_index]
    
    # Normalisasi K-Fold
    train_dataFold = sc.fit_transform(xtrainFold)
    test_dataFold = sc.transform(xtestFold)

    print("\nHasil normalisasi test_data K-Fold:\n", test_dataFold[:3], "...\n", test_dataFold[-3:])

# 3. Metode Leave-One-Out (LOO)
loo = LeaveOneOut()
accuracies = []

for train_index, test_index in loo.split(train_data):
    X_trainLoo, X_testLoo = train_data.iloc[train_index], train_data.iloc[test_index]
    y_trainLoo, y_testLoo = label.iloc[train_index], label.iloc[test_index]
    
    # Normalisasi LOO
    train_dataLoo = sc.fit_transform(X_trainLoo)
    test_dataLoo = sc.transform(X_testLoo)


print("\nHasil normalisasi test_data LOO:\n", test_dataLoo)
print("Akurasi rata-rata LOO: ", np.mean(accuracies))


Hasil normalisasi test_data Hold-out:
 [[1.         0.3106386  1.         0.02975782]
 [1.         0.3842674  0.5        0.02049464]
 [1.         0.24604172 1.         0.01546857]
 ...
 [1.         0.81151043 0.         0.05182215]
 [1.         0.2083438  1.         0.01690807]
 [1.         0.34656949 0.         0.05182215]]

Hasil normalisasi test_data K-Fold:
 [[1.         0.34656949 0.         0.06929139]
 [1.         0.49736115 0.         0.0541074 ]
 [0.         0.17064589 1.         0.02194234]] ...
 [[1.         0.23347575 1.         0.01541158]
 [1.         0.33400352 0.5        0.02537431]
 [1.         0.32143755 0.         0.0585561 ]]

Hasil normalisasi test_data K-Fold:
 [[1.         0.3106386  1.         0.0165095 ]
 [0.         0.04498618 1.         0.03259623]
 [0.         0.4722292  1.         0.06126432]] ...
 [[0.         0.54762503 0.5        0.05074862]
 [1.         0.24604172 1.         0.01921772]
 [0.         0.48479517 1.         0.05684821]]

Hasil normalisasi 

c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


In [14]:
# 6. test_data <- lakukan normalisasi pada train_data dengan min-max pada Langkah 5
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, KFold, LeaveOneOut
import pandas as pd 

test_data = pd.read_csv('titanic_test.csv')
test_data = test_data[['Sex', 'Age', 'Pclass', 'Fare']]
test_data['Sex'] = test_data['Sex'].map({'male':1, 'female':0})
test_data['Age'] = test_data.groupby('Pclass')['Age'].transform(lambda x: x.fillna(x.mean()))
sc = MinMaxScaler(feature_range=(0, 1))

#1. Metode Hold-Out
xtrainHold, xtestHold = train_test_split(test_data, test_size=0.3, random_state=42)
xtrainHold_normalized = sc.fit_transform(xtrainHold)
test_dataHold_normalized = sc.transform(xtestHold)
print("Hasil normalisasi test_data Hold-Out : \n", test_dataHold_normalized[:5])

#2. Metode K-Fold (k=10)
kf = KFold(n_splits=10, shuffle=True, random_state=42)

for train_index, test_index in kf.split(test_data):
    xtrainFold, X_testFold = test_data.iloc[train_index], test_data.iloc[test_index]
    xtrainFold_normalized = sc.fit_transform(xtrainFold)
    test_dataFold_normalized = sc.transform(X_testFold)
    print("\nHasil normalisasi test_data K-Fold:\n", test_dataFold_normalized[:5])
    break 

#3. Metod Leave 
loo = LeaveOneOut()

for train_index, tes_index in loo.split(test_data): 
    xtrainLoo, xtestLoo = test_data.iloc[train_index], test_data.iloc[test_index]
    xtrainLoo_normalized = sc.fit_transform(xtrainLoo)
    test_dataLoo_normalized = sc.transform(xtestLoo)

    print("\n Hasil normalisasi test_data LOO : \n", test_dataLoo_normalized[:5])
    break

Hasil normalisasi test_data Hold-Out : 
 [[1.         0.32602088 1.         0.01411046]
 [0.         0.51103476 0.         0.41250333]
 [1.         0.27315977 1.         0.01512699]
 [1.         0.45817365 1.         0.01541158]
 [0.         0.47138893 1.         0.02378022]]

Hasil normalisasi test_data K-Fold:
 [[1.         0.27469339 1.         0.04713766]
 [1.         0.65712779 0.5        0.05074862]
 [0.         0.3146241  1.         0.04577135]
 [1.         0.3146241  1.         0.11027246]
 [1.         0.12963207 1.         0.05684821]]

 Hasil normalisasi test_data LOO : 
 [[1.         0.27469339 1.         0.04713766]
 [1.         0.65712779 0.5        0.05074862]
 [0.         0.3146241  1.         0.04577135]
 [1.         0.3146241  1.         0.11027246]
 [1.         0.12963207 1.         0.05684821]]


In [15]:
"""
7. Lakukan klasifikasi k-NN (k=3) untuk masing-masing pendekatan validasi dan
hitunglah error ratio-nya
"""
from sklearn.model_selection import train_test_split, KFold, LeaveOneOut
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import numpy as np 
import pandas as pd 

error_ratio = pd.Series([None, None, None])
validasi = ['Hold-Out', 'K-Fold', 'LOO']

# ----- Metode 1: Hold-out -----
print(f"kNN k=3 validation Hold-Out")
knn = KNeighborsClassifier(n_neighbors=3)
xtrainHold, xtestHold, ytrainHold, ytestHold = train_test_split(train_data, label, test_size=0.3, random_state=42)
knn.fit(xtrainHold, ytrainHold)
class_result_Hold = knn.predict(xtestHold)
precision_ratio_Hold = accuracy_score(ytestHold, class_result_Hold)
error_ratio[0] = 1 - precision_ratio_Hold

# Tampilkan hasil prediksi dan error ratio
print(class_result_Hold)
print(f"Error ratio : {round(error_ratio[0] * 100, 2)}%")
print("\n")


# ----- Metode 2: K-Fold (k=10) -----
print(f"kNN k=3 validation K-Fold")
knn = KNeighborsClassifier(n_neighbors=3)

kf = KFold(n_splits=10, shuffle=True, random_state=42)
class_result_Fold_total = []

for train_index, test_index in kf.split(train_data):
    xtrainFold, xtestFold = train_data.iloc[train_index], train_data.iloc[test_index]
    ytrainFold, ytestFold = label.iloc[train_index], label.iloc[test_index]
    knn.fit(xtrainFold, ytrainFold)
    class_result_Fold = knn.predict(xtestFold)
    class_result_Fold_total.extend(class_result_Fold)
precision_ratio_Fold = accuracy_score(label, class_result_Fold_total)
error_ratio_Fold = 1 - precision_ratio_Fold
print(class_result_Fold_total)
print(f"Error ratio : {round(error_ratio_Fold * 100, 2)}%")
print("\n")

# ----- Metode 3: Leave-One-Out (LOO) -----
print(f"kNN k=3 validation LOO")
knn = KNeighborsClassifier(n_neighbors=3)

loo = LeaveOneOut()
class_result_Loo_total = []

for train_index, test_index in loo.split(train_data):
    xtrainLoo, xtestLoo = train_data.iloc[train_index], train_data.iloc[test_index]
    ytrainLoo, ytestLoo = label.iloc[train_index], label.iloc[test_index]
    knn.fit(xtrainLoo, ytrainLoo)
    class_result_Loo = knn.predict(xtestLoo)
    class_result_Loo_total.extend(class_result_Loo)

precision_ratio_Loo = accuracy_score(label, class_result_Loo_total)
error_ratio_Loo = 1 - precision_ratio_Loo

# Tampilkan hasil prediksi dan error ratio
print(class_result_Loo_total)
print(f"Error ratio : {round(error_ratio_Loo * 100, 2)}%")
print("\n")

kNN k=3 validation Hold-Out
[0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0
 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1
 0 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0
 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 1
 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 1 0 0 1 0 1 0 0 1 0 1 0 0 1 1 1 0 0 0 1
 0 1 0 1 0 0 0 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0
 1 0 1 0 0 0 0 0 0]
Error ratio : 30.6%


kNN k=3 validation K-Fold
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 